apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goalrail
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - goalrail.example.com
      secretName: goalrail-tls
  rules:
    - host: goalrail.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: goalrail
                port:
                  name: http
