apiVersion: v1
kind: Service
metadata:
  name: goalrail
  labels:
    app: goalrail
spec:
  type: ClusterIP
  selector:
    app: goalrail
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
