apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: goalrail
  labels:
    app: goalrail
spec:
  host: goalrail.apps.example.com
  to:
    kind: Service
    name: goalrail
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
